remote_theme: civilsteward/hydejacked

keywords: [data governance, data stewardship, stewardship, data steward, steward]

lang: en
url: https://CivilSteward.github.io

title: Civil Steward
description: Establishing Data Governance

sanitize: true

font_heading: Yantamanav, Arial, sans-serif
google_fonts: Yantamanav:400

menu:
  - title:             Learn
    url:               /learn/
  - title:             Connect
    url:               /connect/
  - title:             About
    url:               /about/

# Plugins
# ========================================================================================

plugins:
  - jekyll-default-layout
  - jekyll-feed
  - jekyll-optional-front-matter
  - jekyll-paginate
  - jekyll-readme-index
  - jekyll-redirect-from
  - jekyll-relative-links
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-titles-from-headings
  - jekyll-replace-img

hydejack:
    no_mark_external:    true
