title: Civil Steward
description: Adventures Establishing Data Governance
remote_theme: CivilSteward/hydejack

header_pages:
  - helpful.md
  - connect.md
  - about.md

sanitize: true
show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
menu:
  - title: Learn
    url: /helpful/
  - title: Connect
    url: /connect/
  - title: About
    url: /about/
