title: Civil Steward
description: Adventures Establishing Data Governance

remote_theme: CivilSteward/hydejack
theme_color: rgb(128,0,106)
font: Source Sans Pro, Arial, sans-serif
font_heading: Source Sans pro, Arial, sans-serif
google_fonts: Source+Sans+Pro:400

header_pages:
  - helpful.md
  - connect.md
  - about.md

sanitize: true
show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
menu:
  - title: Learn
    url: /helpful/
  - title: Connect
    url: /connect/
  - title: About
    url: /about/
