title: Civil Steward
description: Adventures Establishing Data Governance

theme: telephasic

sanitize: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
menu:
  - title: Learn
    url: /helpful/
  - title: Connect
    url: /connect/
  - title: About
    url: /about/
