title: Civil Steward
description: Adventures Establishing Data Governance
sanitize: true
theme: civilsteward/minima
header_pages:
  - helpful.md
  - about.md
show_excerpts: true
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
