title: Civil Steward
description: Adventures Establishing Data Governance

remote_theme: andrewbanchich/forty-jekyll-theme

sanitize: true
show_excerpts: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
menu:
  - title: Learn
    url: /helpful/
  - title: Connect
    url: /connect/
  - title: About
    url: /about/
