title: Civil Steward
description: Adventures Establishing Data Governance

theme: minima

sanitize: true

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
header_pages:
  - learn.md
  - connect.md
  - about.md
